name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        goo-slice: [ '100']
        ruby-version: [ '3.2.0']
        triplestore: [ 'fs', 'ag', 'vo', 'gb' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create config.rb file
        run: cp config/config.rb.sample config/config.rb
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get -y install raptor2-utils
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run unit tests
        # unit tests are run inside a container
        # http://docs.codecov.io/docs/testing-with-docker
        run: |
          ci_env=`bash <(curl -s https://codecov.io/env)`
          GOO_SLICES=${{ matrix.goo-slice }} RUBYOPT="-W0" bundle exec rake test:docker:${{ matrix.triplestore }} TESTOPTS="-v"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          verbose: true
          fail_ci_if_error: false # optional (default = false)
